name: MyApp
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: "17.0"
packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    version: 11.6.0
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS
    version: 8.0.0
settings:
  MARKETING_VERSION: "1.0"
  CURRENT_PROJECT_VERSION: "1"
targets:
  MyApp:
    type: application
    platform: iOS
    sources:
      - path: Sources/App
      - path: Sources/Views
      - path: Assets.xcassets
      - path: PrivacyInfo.xcprivacy
      - path: GoogleService-Info.plist
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.example.myapp
      INFOPLIST_FILE: Info.plist
      CODE_SIGN_ENTITLEMENTS: App.entitlements
      PROVISIONING_PROFILE_SPECIFIER: "$(APP_PROFILE_NAME)"
      CODE_SIGN_STYLE: Manual
      CODE_SIGN_IDENTITY: "Apple Distribution"
      DEVELOPMENT_TEAM: "$(TEAM_ID)"
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
      INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
      INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
      INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
      ENABLE_PREVIEWS: YES
      SWIFT_VERSION: "5.9"
      TARGETED_DEVICE_FAMILY: "1,2"
    dependencies:
      - target: ShareExtension
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseDatabase
      - package: Firebase
        product: FirebaseMessaging
      - package: GoogleSignIn
        product: GoogleSignIn
  ShareExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: ShareExtension
      - path: GoogleService-Info.plist
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.example.myapp.ShareExtension
      INFOPLIST_FILE: ShareExtension/Info.plist
      CODE_SIGN_ENTITLEMENTS: ShareExtension.entitlements
      PROVISIONING_PROFILE_SPECIFIER: "$(SHARE_EXTENSION_PROFILE_NAME)"
      CODE_SIGN_STYLE: Manual
      CODE_SIGN_IDENTITY: "Apple Distribution"
      DEVELOPMENT_TEAM: "$(TEAM_ID)"
      SWIFT_VERSION: "5.9"
      TARGETED_DEVICE_FAMILY: "1,2"
      SKIP_INSTALL: YES
      PRODUCT_NAME: ShareExtension
    dependencies:
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseDatabase
